#pragma once
#ifndef TestSort_H
#define TestSort_H
#include "..\LeetCode\LeetCodeSort.h"
void TestLeetCode300(void);
void TestLeetCode315(void);
void TestLeetCode327(void);
void TestLeetCode354(void);
void TestLeetCode373(void);
void TestLeetCode414(void);
void TestLeetCode493(void);
void TestLeetCode632(void);
void TestLeetCode673(void);
void TestLeetCode683(void);
void TestLeetCode774(void);
void TestLeetCode846(void);
void TestLeetCode857(void);
void TestLeetCode1213(void);
void TestLeetCodeSort(void);
#endif  // TestTree
