#pragma once
#ifndef TestHashtable_H
#define TestHashtable_H
#include "..\LeetCode\LeetCodeHashtable.h"
void TestLeetCode1(void);
void TestLeetCode15(void); 
void TestLeetCode454(void);
void TestLeetCode18(void);
void TestLeetCode170(void);
void TestLeetCode535(void);
void TestLeetCode1207(void);
void TestLeetCode1218(void);
void TestLeetCode1224(void);
void TestLeetCode1257(void);
void TestLeetCode1386(void);
void TestLeetCode1394(void);
void TestLeetCode1418(void);
void TestLeetCode1426(void);
void TestLeetCode1452(void);
void TestLeetCode1481(void);
void TestLeetCode1487(void);
void TestLeetCode1496(void);
void TestLeetCode1512(void);
void TestLeetCode1577(void);
void TestLeetCode1604(void);
void TestLeetCode1679(void);
void TestLeetCode1711(void);
void TestLeetCodeHashtable(void);
#endif  // TestHashtable_H