#pragma once
#ifndef TestString_H
#define TestString_H
#include "..\LeetCode\LeetCodeString.h"
void TestLeetCode28(void);
void TestLeetCode58(void);
void TestLeetCode71(void);
void TestLeetCode151(void);
void TestLeetCode165(void);
void TestLeetCode186(void);
void TestLeetCode288(void);
void TestLeetCode415(void);
void TestLeetCode459(void);
void TestLeetCode686(void);
void TestLeetCode796(void);
void TestLeetCode830(void);
void TestLeetCode1165(void);
void TestLeetCode1170(void);
void TestLeetCode1181(void);
void TestLeetCode1189(void);
void TestLeetCode1233(void);
void TestLeetCode1234(void);
void TestLeetCode1247(void);
void TestLeetCode1297(void);
void TestLeetCode1309(void);
void TestLeetCode1316(void);
void TestLeetCodeString(void);
#endif  // TestArray
