#pragma once
#ifndef TestLinkedList_H
#define TestLinkedList_H
#include "..\LeetCode\LeetCodeLinkedList.h"
void TestLeetCode2(void);
void TestLeetCode24(void);
void TestLeetCode19(void);
void TestLeetCode21(void);
void TestLeetCode23(void);
void TestLeetCode25(void);
void TestLeetCode61(void);
void TestLeetCode82(void);
void TestLeetCode86(void);
void TestLeetCode83(void);
void TestLeetCode92(void);
void TestLeetCode138(void);
void TestLeetCode143(void);
void TestLeetCode147(void);
void TestLeetCode148(void);
void TestLeetCode160(void);
void TestLeetCode203(void);
void TestLeetCode206(void);
void TestLeetCode234(void);
void TestLeetCode237(void);
void TestLeetCode328(void);
void TestLeetCode369(void);
void TestLeetCode382(void);
void TestLeetCode427(void);
void TestLeetCode445(void);
void TestLeetCode558(void);
void TestLeetCode708(void);
void TestLeetCode725(void);
void TestLeetCode817(void);
void TestLeetCode876(void);
void TestLeetCode1265(void);
void TestLeetCode1290(void);
void TestLeetCode1019(void);
void TestLeetCode1171(void);
void TestLeetCode1474(void);
void TestLeetCode1634(void);
void TestLeetCode1669(void);
void TestLeetCodeLinkedList(void);
#endif  // TestStack_H