#pragma once
#ifndef TestBFS_H
#define TestBFS_H
#include "..\LeetCode\LeetCodeBFS.h"
void TestLeetCode127(void);
void TestLeetCode130(void);
void TestLeetCode200(void);
void TestLeetCode302(void);
void TestLeetCode417(void);
void TestLeetCode433(void);
void TestLeetCode542(void);
void TestLeetCode690(void);
void TestLeetCode733(void);
void TestLeetCode743(void);
void TestLeetCode752(void);
void TestLeetCode773(void);
void TestLeetCode854(void);
void TestLeetCode864(void);
void TestLeetCode882(void);
void TestLeetCode909(void);
void TestLeetCode924(void);
void TestLeetCode928(void);
void TestLeetCode934(void);
void TestLeetCode967(void);
void TestLeetCode994(void);
void TestLeetCode1020(void);
void TestLeetCode1030(void);
void TestLeetCode1034(void);
void TestLeetCode1042(void);
void TestLeetCode1091(void);
void TestLeetCode1162(void);
void TestLeetCode1284(void);
void TestLeetCode1197(void);
void TestLeetCode1215(void);
void TestLeetCode1334(void);
void TestLeetCodeBFS(void);
#endif  // TestTree
