#pragma once
#ifndef TestUnionFind_H
#define TestUnionFind_H
#include "..\LeetCode\LeetCodeUnionFind.h"
void TestLeetCode305(void);
void TestLeetCode547(void);
void TestLeetCode695(void);
void TestLeetCode721(void);
void TestLeetCode737(void);
void TestLeetCode803(void);
void TestLeetCode827(void);
void TestLeetCode839(void);
void TestLeetCode947(void);
void TestLeetCode952(void);
void TestLeetCode990(void);
void TestLeetCode1061(void);
void TestLeetCode1101(void);
void TestLeetCode1202(void);
void TestLeetCode1319(void);
void TestLeetCode9903(void);
void TestLeetCodeUnionFind(void);
#endif  // TestGraph
