#pragma once
#ifndef TestBinarySearch_H
#define TestBinarySearch_H
#include "..\LeetCode\LeetCodeBinarySearch.h"
void TestLeetCode4(void);
void TestLeetCode33(void);
void TestLeetCode34(void);
void TestLeetCode81(void);
void TestLeetCode153(void);
void TestLeetCode154(void);
void TestLeetCode162(void);
void TestLeetCode240(void);
void TestLeetCode378(void);
void TestLeetCode410(void);
void TestLeetCode719(void);
void TestLeetCode786(void);
void TestLeetCode875(void);
void TestLeetCode1011(void);
void TestLeetCode1231(void);
void TestLeetCode1274(void);
void TestLeetCode1300(void);
void TestLeetCodeBinarySearch(void);
#endif  // TestBinarySearch
