#pragma once
#ifndef TestArray_H
#define TestArray_H
#include "..\LeetCode\LeetCodeArray.h"
void TestLeetCode364(void);
void TestLeetCode36(void);
void TestLeetCode41(void);
void TestLeetCode169(void);
void TestLeetCode287(void);
void TestLeetCode229(void);
void TestLeetCode1198(void);
void TestLeetCode1208(void);
void TestLeetCode1221(void);
void TestLeetCode1222(void);
void TestLeetCode1228(void);
void TestLeetCode53(void);
void TestLeetCode134(void);
void TestLeetCode152(void);
void TestLeetCode325(void);
void TestLeetCode448(void);
void TestLeetCode523(void);
void TestLeetCode525(void);
void TestLeetCode560(void); 
void TestLeetCode930(void);
void TestLeetCode974(void);
void TestLeetCode1243(void);
void TestLeetCode1248(void);
void TestLeetCode48(void);
void TestLeetCode54(void);
void TestLeetCode59(void);
void TestLeetCode1252(void);
void TestLeetCode1253(void);
void TestLeetCode1260(void);
void TestLeetCode1275(void);
void TestLeetCode1282(void);
void TestLeetCode1287(void);
void TestLeetCode1292(void);
void TestLeetCode1296(void);
void TestLeetCode1299(void);
void TestLeetCode1306(void);
void TestLeetCode1310(void);
void TestLeetCodeArray(void);
#endif  // TestArray
