#pragma once
#ifndef TestGreedy_H
#define TestGreedy_H
#include "..\LeetCode\LeetCodeGreedy.h"
void TestLeetCode56(void);
void TestLeetCode57(void);
void TestLeetCode163(void);
void TestLeetCode218(void);
void TestLeetCode1229(void);
void TestLeetCode1272(void);
void TestLeetCode1288(void);
void TestLeetCode1326(void);
void TestLeetCode1353(void);
void TestLeetCode1383(void);
void TestLeetCode1405(void);
void TestLeetCode1419(void);
void TestLeetCode1520(void);
void TestLeetCode1562(void);
void TestLeetCode1589(void);
void TestLeetCode1665(void);
void TestLeetCode1641(void);
void TestLeetCodeGreedy(void);
#endif  // TestArray
