#pragma once
#ifndef TestDFS_H
#define TestDFS_H
#include "..\LeetCode\LeetCodeDFS.h"
void TestLeetCode17(void);
void TestLeetCode37(void);
void TestLeetCode39(void);
void TestLeetCode40(void);
void TestLeetCode51(void);
void TestLeetCode52(void);
void TestLeetCode46(void);
void TestLeetCode47(void);
void TestLeetCode77(void);
void TestLeetCode78(void);
void TestLeetCode79(void);
void TestLeetCode90(void);
void TestLeetCode93(void);
void TestLeetCode126(void);
void TestLeetCode212(void);
void TestLeetCode216(void);
void TestLeetCode241(void);
void TestLeetCode329(void);
void TestLeetCode401(void);
void TestLeetCode416(void);
void TestLeetCode425(void);
void TestLeetCode464(void);
void TestLeetCode473(void);
void TestLeetCode491(void);
void TestLeetCode526(void);
void TestLeetCode996(void);
void TestLeetCode980(void);
void TestLeetCode1066(void);
void TestLeetCode1079(void);
void TestLeetCode1140(void);
void TestLeetCode1219(void);
void TestLeetCode1240(void);
void TestLeetCode1307(void);
void TestLeetCode1349(void);
void TestLeetCode1397(void);
void TestLeetCode1593(void);
void TestLeetCode1595(void);
void TestLeetCode1601(void);
void TestLeetCode1655(void);
void TestLeetCode1659(void);
void TestLeetCode1681(void);
void TestLeetCode1718(void);
void TestLeetCode1728(void);
void TestLeetCode1770(void);
void TestLeetCode1799(void);
void TestLeetCode1766(void);
void TestLeetCode1815(void);
void TestLeetCode1849(void);
void TestLeetCode1879(void);
void TestLeetCodeDFS(void);
#endif  // TestTree
